### PR TITLE
Add a Users.whoami method that returns the logged-in user.

### PR DESCRIPTION
**Pull request by allenap**

### CODE REVIEW

**Comment by brendan-donegan** [comment]
Looks good mostly - little unsure about assigning is_admin randomly, maybe you can enlighten me on that?

**Comment by allenap** [comment]
Thanks!

> little unsure about assigning is_admin randomly, maybe you can enlighten me on that?

It shows that the field is used: eventually the test will fail if the method was implemented with a canned answer.

**Comment by brendan-donegan** [comment]
Wouldn't having two separate tests perform the same function?

**Comment by allenap** [comment]
It would, but that can get tiresome when there are many arguments, especially if they're not from a bounded set like true/false. Here it's saying that the value itself is kind of irrelevant to the test, except that the implementation cannot depend on any particular value, other than it being a boolean. If you're doing strict TDD this is particularly relevant. To really do this right there's [Hypothesis](https://hypothesis.readthedocs.io/) which is rather brilliant, but it can also be complex, and overwhelm and obscure the point of the test.

**Comment by brendan-donegan** [comment]
Yeah, using Hypothesis would be nice, but maybe later

**Pull request merged**
